# Clock and Sync
set_property PACKAGE_PIN U18 [get_ports vid_io_out_0_hsync]
set_property PACKAGE_PIN V20 [get_ports vid_io_out_0_vsync]
set_property PACKAGE_PIN U19 [get_ports vid_io_out_0_active_video]
set_property PACKAGE_PIN V19 [get_ports pixel_clk_0]

# HDMI RGB Data (8 bits each)
set_property PACKAGE_PIN T20 [get_ports {vid_io_out_0_data[0]}]
set_property PACKAGE_PIN U20 [get_ports {vid_io_out_0_data[1]}]
set_property PACKAGE_PIN V21 [get_ports {vid_io_out_0_data[2]}]
set_property PACKAGE_PIN W21 [get_ports {vid_io_out_0_data[3]}]
set_property PACKAGE_PIN W20 [get_ports {vid_io_out_0_data[4]}]
set_property PACKAGE_PIN W19 [get_ports {vid_io_out_0_data[5]}]
set_property PACKAGE_PIN W18 [get_ports {vid_io_out_0_data[6]}]
set_property PACKAGE_PIN V18 [get_ports {vid_io_out_0_data[7]}]
set_property PACKAGE_PIN U17 [get_ports {vid_io_out_0_data[8]}]
set_property PACKAGE_PIN V17 [get_ports {vid_io_out_0_data[9]}]
set_property PACKAGE_PIN W17 [get_ports {vid_io_out_0_data[10]}]
set_property PACKAGE_PIN W16 [get_ports {vid_io_out_0_data[11]}]
set_property PACKAGE_PIN V16 [get_ports {vid_io_out_0_data[12]}]
set_property PACKAGE_PIN U16 [get_ports {vid_io_out_0_data[13]}]
set_property PACKAGE_PIN T15 [get_ports {vid_io_out_0_data[14]}]
set_property PACKAGE_PIN U15 [get_ports {vid_io_out_0_data[15]}]
set_property PACKAGE_PIN V15 [get_ports {vid_io_out_0_data[16]}]
set_property PACKAGE_PIN W15 [get_ports {vid_io_out_0_data[17]}]
set_property PACKAGE_PIN W14 [get_ports {vid_io_out_0_data[18]}]
set_property PACKAGE_PIN V14 [get_ports {vid_io_out_0_data[19]}]
set_property PACKAGE_PIN U14 [get_ports {vid_io_out_0_data[20]}]
set_property PACKAGE_PIN T14 [get_ports {vid_io_out_0_data[21]}]
set_property PACKAGE_PIN V13 [get_ports {vid_io_out_0_data[22]}]
set_property PACKAGE_PIN W13 [get_ports {vid_io_out_0_data[23]}]

# IO Standards
set_property IOSTANDARD LVCMOS33 [get_ports {vid_io_out_0_*}]
set_property IOSTANDARD LVCMOS33 [get_ports pixel_clk_0]
